WANTED_VENUES = [
    "バンテリンドームナゴヤ",
    "IGアリーナ",
    "日本ガイシホール",
    "クロコくんホール",
    "ポートメッセなごや",
    "愛知スカイエキスポ",
    "パロマ瑞穂スタジアム",
    "Zepp Nagoya",
    "DIAMOND HALL",
    "ダイヤモンドホール",
    "ダイアモンドホール",
    "COMTEC PORTBASE",
    "ポートベース",
    "愛知県芸術劇場",
    "中日ホール",
    "中電ホール",
    "Niterra日本特殊陶業市民会館",
    "岡谷鋼機名古屋公会堂",
    "名古屋公会堂",
    "御園座",
    "吹上ホール",
    "モリコロパーク",
    "愛・地球博記念公園",
    "大高緑地",
    "SAKAE SP-RING",
]
def is_wanted_venue(venue):
    return any(v in venue for v in WANTED_VENUES)
